### ISSUE TITLE
pset_read'ing a slot which has no data crashes grid

### ISSUE THREAD

**Issue by dndrks** [monome/iii#17]
**steps to repro**
- execute `pset_read(n)` where `n` is a slot with no data yet saved to it

**expected**
no data is returned

**experienced**
grid freezes and is unresponsive to press + diii commands until hot-plugged

**Comment by tehn** [comment]
fixed in 250129

**Comment by dndrks** [comment]
hihi! still experiencing `pset_read` crashes with `250201`.

test script:
```lua
print("hi!")
metro.new(function(x)
  if x == 1 then
    print("going to read a blank pset!")
  elseif x == 2 then
    print('reading PSET "10"')
    pset_read(10)
  elseif x == 3 then
    print("did we get here?")
  end
end, 600, 3)
```

lmk if there's anything else i can provide!

**Comment by tehn** [comment]
confirmed.

if you try to flash_read() on an uninitialized flash slot it will potentially try to return a huge long string with unpredictable results. if run from pset_read it will attempt to execute this and break.

i added a fix to clear the flash area when uploading the firmware for the first time.

to fix this in beta, run:

```
for i=1,256 do flash_clear(i) end
```

or better yet, i'm considering adding some metadata to the pset system so it is aware of which flash slots have been written, hence which are safe to load.

before that happens, you can roll your own. (i did this in another script, just a table that gets stored to slot 1 with metadata of which psets are legit)

**Comment by tehn** [comment]
fixed in next version.
